website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func
from flask_sqlalchemy import SQLAlchemy



class Reservation(db.Model):
    __tablename__ = 'reservation'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    ticket_id = db.Column(db.Integer, db.ForeignKey('ticket.id'))
    guide_id = db.Column(db.Integer, db.ForeignKey('guide.id'))
    safari_id = db.Column(db.Integer, db.ForeignKey('safari.id'))
    sum_price = db.Column(db.Integer)
    # date = db.Column(db.DateTime)
    tickets = db.relationship('Ticket')
    users = db.relationship('User')
    #guides = db.relationship('Guide')
    safari = db.relationship('Safari')
    

    

class Safari(db.Model):
    __tablename__ = 'safari'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    type = db.Column(db.String(15000))
    seats = db.Column(db.Integer, nullable = False, default = 20)
    

class Guide(db.Model):
    __tablename__  = 'guide'
    id = db.Column(db.Integer, primary_key=True)
    guide_name = db.Column(db.String(1500))
    surname = db.Column(db.String(1500))

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    # user_name = db.Column(db.String(150))
    # phone_number = db.Column(db.Integer)
    tickets = db.relationship('Ticket')
    reservation = db.relationship('Reservation')


class Ticket(db.Model):
    __tablename__ = 'ticket'
    id = db.Column(db.Integer, primary_key =True)
    price = db.Column(db.Integer)
    amount = db.Column(db.Integer)
    type = db.Column(db.String(150))
    ticket_date = db.Column(db.String(150), db.ForeignKey('safari.date'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    users = db.relationship('User')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "C:\\Users\\Marcin\\Desktop\\github\\SafariReservation\\instance\\database.db"



def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hellotherethisisthepsswd'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        from .models import User
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db 
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, url_for, render_template, request, flash, jsonify, redirect
from flask_login import login_required, current_user
from .models import Safari, Ticket, Reservation, User, Guide
from . import db
from sqlalchemy.sql import text, select
import json, datetime

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    user_id = current_user.id
    reservations = Reservation.query.filter_by(user_id = user_id)
    return render_template("home.html", user=current_user, reservations = reservations)


@views.route('/create-reservation', methods=['POST'])
def create_reservation():
    print("DANE: ", request.form)
    date_str = request.form.get("date_safari")
    date = datetime.datetime.strptime(date_str, '%Y-%m-%dT%H:%M')
    safari = Safari.query.filter_by(date=date).first()
    ticket = Ticket(type = request.form.get("package1"), amount = request.form.get("package3"),
                    ticket_date = date, users = current_user)

    if safari:
        if safari.seats >= int(request.form.get("package3")):
            safari.seats -= int(request.form.get("package3"))
        
        elif safari.seats < int(request.form.get("package3")) and safari.seats > 1:
            flash('There is only ' + str(safari.seats) +' seats left', category='error')
            return redirect('/')
        
        elif safari.seats == 1:
            flash('There is only ' + str(safari.seats) +' seat left', category='error')
            return redirect('/')
      
        else:
            flash('No more seats left:(', category='error')
            return redirect('/')
    else:
        
        safari = Safari(date = date, type = request.form.get("package2"))
        safari.seats = 20 - int(ticket.amount)
        db.session.add(safari)

    reservation = Reservation(safari=safari, tickets=ticket, users=current_user)
    db.session.add(ticket)
    db.session.add(reservation)
    db.session.commit()   
    return redirect('/')

@views.route('/delete-reservation/<int:id>', methods=['POST'])
def delete_reservation(id):
    reservations = Reservation.query.get(id)
    safari = reservations.safari
    safari.seats += reservations.tickets.amount
    tickets = reservations.tickets
    db.session.delete(tickets)
    db.session.delete(reservations)
    db.session.commit()
    return redirect('/')

@views.route('/admin', methods=['GET', 'POST'])
def admin():
    reservations = Reservation.query.all()
    user_id = current_user.id
    return render_template('admin.html',user = current_user, reservations=reservations)

website/templates/admin.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
%}

<body>
    <h3>Reservations</h3>
    <a href="/admin"></a>
    <br>
    <table>
      <thead>
        <th style="border: 1px solid black;">Id</th>
        <th style="border: 1px solid black;">userID</th>
        <th style="border: 1px solid black;">safariID</th>
        <th style="border: 1px solid black;">ticketID</th>
        <th style="border: 1px solid black;">Date</th>
        <th style="border: 1px solid black;">sumPrice</th>
        <!-- <th style="border: 1px solid black;">#</th> -->
     </thead>
       {% for reservation in reservations %}
       <tbody>
          <td style="border: 1px solid black;">{{reservation.id}}</td>
          <td style="border: 1px solid black;">{{reservation.user_id}}</td>
          <td style="border: 1px solid black;">{{reservation.safari_id}}</td>
          <td style="border: 1px solid black;">{{reservation.ticket_id}}</td>
          <td style="border: 1px solid black;">{{reservation.safari.date}}</td>
          <td style="border: 1px solid black;">{{reservation.sum_price}}</td>
          <td style="border: 1px solid black;">
            <form action="{{ url_for('views.delete_reservation', id=reservation.id) }}" method="post">
              <input type="submit" value="Delete">
          </form>
          </td>
       </tbody>
       {% endfor%}
      </table>
  </body>
  {% endblock %}
      

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <!-- <script type="text/javascript"> -->
      <!-- function deleteNote(noteId) { -->
  <!-- fetch("/delete-note", { -->
    <!-- method: "POST", -->
    <!-- body: JSON.stringify({ noteId: noteId }), -->
  <!-- }).then((_res) => { -->
    <!-- window.location.href = "/"; -->
  <!-- }); -->
  <!-- } -->
<!-- </script> -->
{% endblock %}
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}

<h1 align="center">Zarezerwuj Safari!</h1>

<form  action="/create-reservation" method="POST">
  <br />
  <div align="center">
    <h4>
      Wybierz rodzaj ulgi:
      </h4>
      Normalny
      <input type="radio" checked = "true" name="package1" value="full">
      Ulgowy
      <input type="radio"  name="package1" value="reduced"> 

      <h4>
        Wybierz typ safari:
      </h4>
      
      Małe zwierzęta
      <input type="radio" checked = "true" name="package2" value="small">
      Duże zwierzęta 
      <input type="radio"  name="package2" value="big">  
      Full Pakiet
      <input type="radio" name="package2" value="all">
  
    <h4>
      Wybierz typ safari:
      </h4>
        
      Małe zwierzęta
      <input type="radio" checked = "true" name="package2" value="small">
      Duże zwierzęta 
      <input type="radio"  name="package2" value="big">  
      Full Pakiet
      <input type="radio" name="package2" value="all">
 
      <h4>
        Wybierz date:
        </h4>
      <input type="datetime-local" id="date_safari" name="date_safari" value="2018-06-12T19:30">

      <h4>
        Wybierz ilość biletów:
        </h4>

        <input type="number" min="1" max="10" name="package3" value="1">
         
        
        <input type="submit" value="rezerwuj"/>
  </div>
</form>

<body>
  <h3>Reservations</h3>
  <a href="/home"></a>
  <br>
  <table>
    <thead>
      <th style="border: 1px solid black;">Id</th>
      <th style="border: 1px solid black;">userID</th>
      <th style="border: 1px solid black;">safariID</th>
      <th style="border: 1px solid black;">ticketID</th>
      <th style="border: 1px solid black;">Date</th>
      <th style="border: 1px solid black;">sumPrice</th>
      <!-- <th style="border: 1px solid black;">#</th> -->
   </thead>
     {% for reservation in reservations %}
     <tbody>
        <td style="border: 1px solid black;">{{reservation.id}}</td>
        <td style="border: 1px solid black;">{{reservation.user_id}}</td>
        <td style="border: 1px solid black;">{{reservation.safari_id}}</td>
        <td style="border: 1px solid black;">{{reservation.ticket_id}}</td>
        <td style="border: 1px solid black;">{{reservation.safari.date}}</td>
        <td style="border: 1px solid black;">{{reservation.sum_price}}</td>
        <td style="border: 1px solid black;">
          <form action="{{ url_for('views.delete_reservation', id=reservation.id) }}" method="post">
            <input type="submit" value="Delete">
        </form>
        </td>
     </tbody>
     {% endfor%}
    </table>
</body>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}